sudo: true
language: node_js
node_js:
- node
git:
  quiet: true
cache: npm

before_install:
- openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv
  -in deploy-key.enc -out deploy-key -d
- chmod 600 ~/.ssh/deploy-key
after_success:
  - bash ./deploy.sh
notifications:
  email: false