export const GET_MENU = "GET_MENU";
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS";
export const GET_MENU_FAILED = "GET_MENU_FAILED";

export const GET_SEARCH_RESULT = "GET_SEARCH_RESULT";
export const GET_SEARCH_RESULT_SUCCESS = "GET_SEARCH_RESULT_SUCCESS";
export const GET_SEARCH_RESULT_FAILED = "GET_SEARCH_RESULT_FAILED";

export const GET_SEARCH_LISTING_PRODUCTS = "GET_SEARCH_LISTING_PRODUCTS";
export const GET_SEARCH_LISTING_PRODUCTS_SUCCESS =
  "GET_SEARCH_LISTING_PRODUCTS_SUCCESS";
export const GET_SEARCH_LISTING_PRODUCTS_FAILED =
  "GET_SEARCH_LISTING_PRODUCTS_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_DECREMENT_QANTITY = "INCREMENT_DECREMENT_QANTITY";

export const GET_HOMEPAGE_BANNER = "GET_HOMEPAGE_BANNER";
export const GET_HOMEPAGE_BANNER_SUCCESS = "GET_HOMEPAGE_BANNER_SUCCESS";
export const GET_HOMEPAGE_BANNER_FAILED = "GET_HOMEPAGE_BANNER_FAILED";

export const GET_HOMEPAGE_PRODUCTS = "GET_HOMEPAGE_PRODUCTS";
export const GET_HOMEPAGE_PRODUCTS_SUCCESS = "GET_HOMEPAGE_PRODUCTS_SUCCESS";
export const GET_HOMEPAGE_PRODUCTS_FAILED = "GET_HOMEPAGE_PRODUCTS_FAILED";

export const GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS";
export const GET_CATEGORY_PRODUCTS_SUCCESS = "GET_CATEGORY_PRODUCTS_SUCCESS";
export const GET_CATEGORY_PRODUCTS_FAILED = "GET_CATEGORY_PRODUCTS_FAILED";

export const GET_SUBCATEGORY_PRODUCTS = "GET_SUBCATEGORY_PRODUCTS";
export const GET_SUBCATEGORY_PRODUCTS_SUCCESS =
  "GET_SUBCATEGORY_PRODUCTS_SUCCESS";
export const GET_SUBCATEGORY_PRODUCTS_FAILED =
  "GET_SUBCATEGORY_PRODUCTS_FAILED";

export const GET_BRANDLISTING = "GET_BRANDLISTING_PRODUCTS";
export const GET_BRANDLISTING_SUCCESS = "GET_BRANDLISTING_SUCCESS";
export const GET_BRANDLISTING_FAILED = "GET_BRANDLISTING_FAILED";

export const GET_BRAND_PAGE_PRODUCTS = "GET_BRAND_PAGE_PRODUCTS_LIST";
export const GET_BRAND_PAGE_PRODUCTS_SUCCESS =
  "GET_BRAND_PAGE_PRODUCTS_SUCCESS";
export const GET_BRAND_PAGE_PRODUCTS_FAILED = "GET_BRAND_PAGE_PRODUCTS_FAILED";

export const GET_BRAND_PAGE_CATEGORY_LIST = "GET_BRAND_PAGE_CATEGORY_LIST_LIST";
export const GET_BRAND_PAGE_CATEGORY_LIST_SUCCESS =
  "GET_BRAND_PAGE_CATEGORY_LIST_SUCCESS";
export const GET_BRAND_PAGE_CATEGORY_LIST_FAILED =
  "GET_BRAND_PAGE_CATEGORY_LIST_FAILED";

export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL";

export const POST_CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const POST_CHECKOUT_REQUEST_SUCCESS = "CHECKOUT_REQUEST_SUCCESS";
export const POST_CHECKOUT_REQUEST_FAIL = "CHECKOUT_REQUEST_FAIL";

export const GET_CITIES_LISTINGS = "GET_CITIES_LISTINGS";
export const GET_CITIES_LISTINGS_SUCCESS = "GET_CITIES_LISTINGS_SUCCESS";
export const GET_CITIES_LISTINGS_FAIL = "GET_CITIES_LISTINGS_FAIL";

export const POST_ASK_QUESTION = "POST_ASK_QUESTION";
export const POST_ASK_QUESTION_SUCCESS = "POST_ASK_QUESTION_SUCCESS";
export const POST_ASK_QUESTION_FAIL = "POST_ASK_QUESTION_FAIL";

export const POST_REVIEW = "POST_REVIEW";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAIL = "POST_REVIEW_FAIL";

export const GET_PRODUCT_REVIEWS = "GET_PRODUCT_REVIEWS";
export const GET_PRODUCT_REVIEWS_SUCCESS = "GET_PRODUCT_REVIEWS_SUCCESS";
export const GET_PRODUCT_REVIEWS_FAIL = "GET_PRODUCT_REVIEWS_FAIL";

export const GET_PRODUCT_QUESTIONS = "GET_PRODUCT_QUESTIONS";
export const GET_PRODUCT_QUESTIONS_SUCCESS = "GET_PRODUCT_QUESTIONS_SUCCESS";
export const GET_PRODUCT_QUESTIONS_FAIL = "GET_PRODUCT_QUESTIONS_FAIL";

export const POST_VERIFY_STOCK = "POST_VERIFY_STOCK";
export const POST_VERIFY_STOCK_SUCCESS = "POST_VERIFY_STOCK_SUCCESS";
export const POST_VERIFY_STOCK_FAIL = "POST_VERIFY_STOCK_FAIL";

export const POST_VERIFY_PHONE = "POST_VERIFY_PHONE";
export const POST_VERIFY_PHONE_SUCCESS = "POST_VERIFY_PHONE_SUCCESS";
export const POST_VERIFY_PHONE_FAIL = "POST_VERIFY_PHONE_FAIL";

export const GET_SUBCATEGORY_FEATURES = "GET_SUBCATEGORY_FEATURES";
export const GET_SUBCATEGORY_FEATURES_SUCCESS =
  "GET_SUBCATEGORY_FEATURES_SUCCESS";
export const GET_SUBCATEGORY_FEATURES_FAIL = "GET_SUBCATEGORY_FEATURES_FAIL";

export const GET_BEST_SELLER_PRODUCTS = "GET_BEST_SELLER_PRODUCTS";
export const GET_BEST_SELLER_PRODUCTS_SUCCESS =
  "GET_BEST_SELLER_PRODUCTS_SUCCESS";
export const GET_BEST_SELLER_PRODUCTS_FAIL = "GET_BEST_SELLER_PRODUCTS_FAIL";

export const GET_FLASH_SALE_PRODUCTS = "GET_FLASH_SALE_PRODUCTS";
export const GET_FLASH_SALE_PRODUCTS_SUCCESS =
  "GET_FLASH_SALE_PRODUCTS_SUCCESS";
export const GET_FLASH_SALE_PRODUCTS_FAIL = "GET_FLASH_SALE_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAIL_SIMILAR_PRODUCTS =
  "GET_PRODUCT_DETAIL_SIMILAR_PRODUCTS";
export const GET_PRODUCT_DETAIL_SIMILAR_PRODUCTS_SUCCESS =
  "GET_PRODUCT_DETAIL_SIMILAR_PRODUCTS_SUCCESS";
export const GET_PRODUCT_DETAIL_SIMILAR_PRODUCTS_FAIL =
  "GET_PRODUCT_DETAIL_SIMILAR_PRODUCTS_FAIL";

export const GET_NEW_ARRIVAL_PRODUCTS = "GET_NEW_ARRIVAL_PRODUCTS";
export const GET_NEW_ARRIVAL_PRODUCTS_SUCCESS =
  "GET_NEW_ARRIVAL_PRODUCTS_SUCCESS";
export const GET_NEW_ARRIVAL_PRODUCTS_FAIL = "GET_NEW_ARRIVAL_PRODUCTS_FAIL";

export const GET_ALL_BEST_SELLER_PRODUCTS = "GET_ALL_BEST_SELLER_PRODUCTS";
export const GET_ALL_BEST_SELLER_PRODUCTS_SUCCESS =
  "GET_ALL_BEST_SELLER_PRODUCTS_SUCCESS";
export const GET_ALL_BEST_SELLER_PRODUCTS_FAIL =
  "GET_ALL_BEST_SELLER_PRODUCTS_FAIL";

export const GET_UNDER_THOUSAND_PRODUCTS = "GET_UNDER_THOUSAND_PRODUCTS";
export const GET_UNDER_THOUSAND_PRODUCTS_SUCCESS =
  "GET_UNDER_THOUSAND_PRODUCTS_SUCCESS";
export const GET_UNDER_THOUSAND_PRODUCTS_FAIL =
  "GET_UNDER_THOUSAND_PRODUCTS_FAIL";

export const POST_SUBSCRIBE_NEWSLETTER = "POST_SUBSCRIBE_NEWSLETTER";

export const POST_CONTACT_US = "POST_CONTACT_US";
export const POST_CONTACT_US_SUCCESS = "POST_CONTACT_US_SUCCESS";
export const POST_CONTACT_US_FAIL = "POST_CONTACT_US_FAIL";

export const POST_NOTIFY_ME = "POST_NOTIFY_ME";
export const POST_NOTIFY_ME_SUCCESS = "POST_NOTIFY_ME_SUCCESS";
export const POST_NOTIFY_ME_FAIL = "POST_NOTIFY_ME_FAIL";

export const GET_SALE_LISTING = "GET_SALE_LISTING";
export const GET_SALE_LISTING_SUCCESS = "GET_SALE_LISTING_SUCCESS";
export const GET_SALE_LISTING_FAIL = "GET_SALE_LISTING_FAIL";

export const POST_TRACK_ORDER = "POST_TRACK_ORDER";
export const POST_TRACK_ORDER_SUCCESS = "POST_TRACK_ORDER_SUCCESS";
export const POST_TRACK_ORDER_FAIL = "POST_TRACK_ORDER_FAIL";

export const POST_VERIFY_LOGIN = "POST_VERIFY_LOGIN";
export const POST_VERIFY_LOGIN_SUCCESS = "POST_VERIFY_LOGIN_SUCCESS";
export const POST_VERIFY_LOGIN_FAIL = "POST_VERIFY_LOGIN_FAIL";

export const POST_THIRD_PARTY_LOGIN = "POST_THIRD_PARTY_LOGIN";
export const POST_THIRD_PARTY_LOGIN_SUCCESS = "POST_THIRD_PARTY_LOGIN_SUCCESS";
export const POST_THIRD_PARTY_LOGIN_FAIL = "POST_THIRD_PARTY_LOGIN_FAIL";

export const POST_VERIFY_PASSWORD = "POST_VERIFY_PASSWORD";
export const POST_VERIFY_PASSWORD_SUCCESS = "POST_VERIFY_PASSWORD_SUCCESS";
export const POST_VERIFY_PASSWORD_FAIL = "POST_VERIFY_PASSWORD_FAIL";

export const POST_SIGN_UP = "POST_SIGN_UP";
export const POST_SIGN_UP_SUCCESS = "POST_SIGN_UP_SUCCESS";
export const POST_SIGN_UP_FAIL = "POST_SIGN_UP_FAIL";

export const POST_RECOVER_PASSWORD = "POST_RECOVER_PASSWORD";
export const POST_RECOVER_PASSWORD_SUCCESS = "POST_RECOVER_PASSWORD_SUCCESS";
export const POST_RECOVER_PASSWORD_FAIL = "POST_RECOVER_PASSWORD_FAIL";

export const GET_CAMPAIGN_LISTING = "GET_CAMPAIGN_LISTING";
export const GET_CAMPAIGN_LISTING_SUCCESS = "GET_CAMPAIGN_LISTING_SUCCESS";
export const GET_CAMPAIGN_LISTING_FAIL = "GET_CAMPAIGN_LISTING_FAIL";

export const GET_FREE_GIFTS = "GET_FREE_GIFTS";
export const GET_FREE_GIFTS_SUCCESS = "GET_FREE_GIFTS_SUCCESS";
export const GET_FREE_GIFTS_FAIL = "GET_FREE_GIFTS_FAIL";

export const POST_VERIFY_PHONE_REGISTER = "POST_VERIFY_REGISTER_PHONE";
export const POST_VERIFY_PHONE_REGISTER_SUCCESS =
  "POST_VERIFY_PHONE_REGISTER_SUCCESS";
export const POST_VERIFY_PHONE_REGISTER_FAIL =
  "POST_VERIFY_PHONE_REGISTER_FAIL";

export const POST_VERIFY_EMAIL = "POST_VERIFY_EMAIL";
export const POST_VERIFY_EMAIL_SUCCESS = "POST_VERIFY_EMAIL_SUCCESS";
export const POST_VERIFY_EMAIL_FAIL = "POST_VERIFY_EMAIL_FAIL";

export const POST_VERIFY_PIN = "POST_VERIFY_PIN";
export const POST_VERIFY_PIN_SUCCESS = "POST_VERIFY_PIN_SUCCESS";
export const POST_VERIFY_PIN_FAIL = "POST_VERIFY_PIN_FAIL";

export const POST_SEND_PIN = "POST_SEND_PIN";
export const POST_SEND_PIN_SUCCESS = "POST_SEND_PIN_SUCCESS";
export const POST_SEND_PIN_FAIL = "POST_SEND_PIN_FAIL";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

export const POST_EDIT_USER_PROFILE = "POST_EDIT_USER_PROFILE";
export const POST_EDIT_USER_PROFILE_SUCCESS = "POST_EDIT_USER_PROFILE_SUCCESS";
export const POST_EDIT_USER_PROFILE_FAIL = "POST_EDIT_USER_PROFILE_FAIL";

export const GET_ALL_ADDRESSES = "GET_ALL_ADDRESSES";
export const GET_ALL_ADDRESSES_SUCCESS = "GET_ALL_ADDRESSES_SUCCESS";
export const GET_ALL_ADDRESSES_FAIL = "GET_ALL_ADDRESSES_FAIL";

export const POST_ADD_ADDRESS = "POST_ADD_ADDRESS";
export const POST_ADD_ADDRESS_SUCCESS = "POST_ADD_ADDRESS_SUCCESS";
export const POST_ADD_ADDRESS_FAIL = "POST_ADD_ADDRESS_FAIL";

export const GET_MY_ORDERS = "GET_MY_ORDERS";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL";

export const POST_RESET_PASSWORD = "POST_RESET_PASSWORD";
export const POST_RESET_PASSWORD_SUCCESS = "POST_RESET_PASSWORD_SUCCESS";
export const POST_RESET_PASSWORD_FAIL = "POST_RESET_PASSWORD_FAIL";

export const POST_UPLOAD_PROFILE_IMAGE = "POST_UPLOAD_PROFILE_IMAGE";
export const POST_UPLOAD_PROFILE_IMAGE_SUCCESS =
  "POST_UPLOAD_PROFILE_IMAGE_SUCCESS";
export const POST_UPLOAD_PROFILE_IMAGE_FAIL = "POST_UPLOAD_PROFILE_IMAGE_FAIL";

export const POST_VERIFY_PHONE_RESET_PASSWORD =
  "POST_VERIFY_PHONE_RESET_PASSWORD";
export const POST_VERIFY_PHONE_RESET_PASSWORD_SUCCESS =
  "POST_VERIFY_PHONE_RESET_PASSWORD_SUCCESS";
export const POST_VERIFY_PHONE_RESET_PASSWORD_FAIL =
  "POST_VERIFY_PHONE_RESET_PASSWORD_FAIL";

/// None Network call probablly use to empty
export const GET_SEARCH_RESULT_EMPTY = "GET_SEARCH_RESULT_EMPTY";
export const PRODUCT_DETAIL_PAGE_EMPTY = "PRODUCT_DETAIL_PAGE_EMPTY";
export const BRAND_PAGE_EMPTY = "BRAND_PAGE_EMPTY";
export const SUBCATEGORY_PAGE_EMPTY = "SUBCATEGORY_PAGE_EMPTY";
export const EMPTY_CATEGORY_PRODUCTS = "EMPTY_CATEGORY_PRODUCTS";

export const GET_WISHLIST = "GET_WISHLIST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAIL = "GET_WISHLIST_FAIL";

export const GET_LOREAL = "GET_LOREAL";
export const GET_LOREAL_SUCCESS = "GET_LOREAL_SUCCESS";
export const GET_LOREAL_FAIL = "GET_LOREAL_FAIL";

export const GET_KERASTASE = "GET_KERASTASE";
export const GET_KERASTASE_SUCCESS = "GET_KERASTASE_SUCCESS";
export const GET_KERASTASE_FAIL = "GET_KERASTASE_FAIL";

export const GET_LOREAL_Extend = "GET_LOREAL_Extend";
export const GET_LOREAL_Extend_SUCCESS = "GET_LOREAL_Extend_SUCCESS";
export const GET_LOREAL_Extend_FAIL = "GET_LOREAL_Extend_FAIL";

export const DELETE_WISHLIST = "DELETE_WISHLIST";
export const DELETE_WISHLIST_SUCCESS = "DELETE_WISHLIST_SUCCESS";
export const DELETE_WISHLIST_FAIL = "DELETE_WISHLIST_FAIL";

export const ADD_WISHLIST = "ADD_WISHLIST";
export const ADD_WISHLIST_SUCCESS = "ADD_WISHLIST_SUCCESS";
export const ADD_WISHLIST_FAIL = "ADD_WISHLIST_FAIL";

export const POST_ADDRESS_MAKE_DEFAULT = "POST_ADDRESS_MAKE_DEFAULT";
export const POST_ADDRESS_MAKE_DEFAULT_SUCCESS =
  "POST_ADDRESS_MAKE_DEFAULT_SUCCESS";
export const POST_ADDRESS_MAKE_DEFAULT_FAIL = "POST_ADDRESS_MAKE_DEFAULT_FAIL";

export const POST_DELETE_ADDRESS = "POST_DELETE_ADDRESS_DEFAULT";
export const POST_DELETE_ADDRESS_SUCCESS = "POST_DELETE_ADDRESS_SUCCESS";
export const POST_DELETE_ADDRESS_FAIL = "POST_DELETE_ADDRESS_FAIL";

export const POST_EDIT_ADDRESS = "POST_EDIT_ADDRESS";
export const POST_EDIT_ADDRESS_SUCCESS = "POST_EDIT_ADDRESS_SUCCESS";
export const POST_EDIT_ADDRESS_FAIL = "POST_EDIT_ADDRESS_FAIL";

export const POST_TRACK_COMPLAINT = "POST_TRACK_COMPLAINT";
export const POST_TRACK_COMPLAINT_SUCCESS = "POST_TRACK_COMPLAINT_SUCCESS";
export const POST_TRACK_COMPLAINT_FAIL = "POST_TRACK_COMPLAINT_FAIL";

export const GET_COMPLAINT_DATA = "GET_COMPLAINT_DATA";
export const GET_COMPLAINT_DATA_SUCCESS = "GET_COMPLAINT_DATA_SUCCESS";
export const GET_COMPLAINT_DATA_FAIL = "GET_COMPLAINT_DATA_FAIL";

export const POST_COMPLAINT_DATA = "POST_COMPLAINT_DATA";
export const POST_COMPLAINT_DATA_SUCCESS = "POST_COMPLAINT_DATA_SUCCESS";
export const POST_COMPLAINT_DATA_FAIL = "POST_COMPLAINT_DATA_FAIL";
export const POST_COMPLAINT_IMAGE = "POST_COMPLAINT_IMAGES";

export const GET_CHECKOUT_PRODUCTS = "GET_CHECKOUT_PRODUCTS";
export const GET_CHECKOUT_PRODUCTS_SUCCESS = "GET_CHECKOUT_PRODUCTS_SUCCESS";
export const GET_CHECKOUT_PRODUCTS_FAIL = "GET_CHECKOUT_PRODUCTS_FAIL";

export const RESTORE_CART = "RESTORE_CART";

export const EMPTY_CART = "EMPTY_CART";

export const EMPTY_USER = "EMPTY_USER";

export const GET_MANISO_MENU = "GET_MANISO_MENU";
export const SET_MANISO_MENU = "SET_MANISO_MENU";

export const GET_MINISO_PRODUCTS = "GET_MINISO_PRODUCTS";
export const SET_MINISO_PRODUCT = "SET_MINISO_PRODUCT";

export const GET_MINISO_CATEGORYPRODUCT = "GET_MINISO_CATEGORYPRODUCT";
export const SET_MINISO_CATEGORYPRODUCT = "SET_MINISO_CATEGORYPRODUCT";

export const GET_MINISO_SUBCATEGORY = "GET_MINISO_SUBCATEGORY";
export const SET_MINISO_SUBCATEGORY = "SET_MINISO_SUBCATEGORY";
